apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-xfusion
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/finance"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-xfusion
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-xfusion
spec:
  containers:
  - name: container-xfusion
    image: nginx:latest
    volumeMounts:
    - name: finance
      mountPath: /usr/share/nginx/html
  volumes:
  - name: finance
    persistentVolumeClaim:
      claimName: pvc-xfusion
---
apiVersion: v1
kind: Service
metadata:
  name: web-xfusion
spec:
  selector:
    app: pod-xfusion
  type: NodePort
  ports:
  - port: 80
    nodePort: 30008
    protocol: TCP