apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: datacenter 
spec:
  schedule: "*/11 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-datacenter
              image: nginx:latest
              command:
                - /bin/sh
                - -c
                - echo Welocme to xfusioncorp
          restartPolicy: OnFailure