apiVersion: v1
kind: Namespace
metadata:
  name: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: dev-nginx-pod
  namespace: dev
spec:
  containers:
  - name: nginx-container
    image: nginx:latest


# Run: kubectl apply -f dev-nginx-pod.yaml


# Validate: 

  #kubectl get namespace
  # NAME                 STATUS   AGE
  # default              Active   59m
  # dev                  Active   59s

  #kubectl get pods -n dev
  # NAME            READY   STATUS    RESTARTS   AGE
  # dev-nginx-pod   1/1     Running   0          36s
