- name: Create a blank file on app servers
  hosts: appservers
  become: yes
  tasks:
    - name: Create a file /opt/code.txt
      file:
        path: /tmp/nfsdata.txt
        state: touch
        mode: 0755
      tags: create_file
    - name: Set the owner of /tmp/nfsdata.txt
      file:
        path: /tmp/nfsdata.txt
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
---
- name: Validate file creation
  hosts: appservers
  tasks:
    - name: Display ls of /opt
      command: ls /opt
      register: ls_result

    - name: Display contents of ls_result
      debug:
        var: ls_result